sudo: required # This ensures more memory (https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System)

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: osx
      language: generic
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - os: osx
      language: generic
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - MACOS_SWIFT_TESTS=true
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - IOS_SWIFT_TESTS=true
    - os: linux
      language: python
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - KOTLIN_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - RUST_TESTS=true
    - os: linux
      language: rust
      rust: beta
      env:
        - RUST_TESTS=true
    - os: linux
      language: rust
      rust: nightly
      env:
        - RUST_TESTS=true

before_install: |
  # Install Rust
  if [ -z ${TRAVIS_RUST_VERSION+w} ]; then
    curl https://sh.rustup.rs -sSf | bash -s -- -y
  fi

  if [ $TRAVIS_OS_NAME == "osx" ]; then
    if [ $PYTHON_TESTS == true ]; then
      # install pyenv
      git clone --depth 1 https://github.com/pyenv/pyenv ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

      case "${TOXENV}" in
        "py27")
          pyenv install 2.7.14
          pyenv global 2.7.14
          ;;
        "py36")
          pyenv install 3.6.1
          pyenv global 3.6.1
          ;;
      esac
      pyenv rehash

      # A manual check that the correct version of Python is running.
      python --version
    fi

    if [ $IOS_SWIFT_TESTS == true ]; then
      PATH="$HOME/.cargo/bin:$PATH"
      rustup target install x86_64-apple-ios
    fi
  fi

install: ./.travis/install.sh

script: ./.travis/test.sh

git:
  depth: 10
